### PR TITLE
set compat to julia >= 1.9

### PR DESCRIPTION
**Pull request by jeremiedb**

### CODE REVIEW

**Comment by jeremiedb** [comment]
@pat-alt Adding tests on Julia <1.9 revealed that there appear to be issues associated with the Optimisers' explicit parametrization approach. Learning seems essentially to fail when running on Julia <v1.9. 
I couldn't find back the discussions around it in Flux while making the transition to Optimisers.jl, only this: https://github.com/FluxML/Flux.jl/issues/1986. 

As a initial measure, I'd go with the lower bound to Julia v1.9. If there's a clean way to add back compatibility to Julia v1.6 I'd for sure consider it, but hopefully most potential users are operating on Julia 1.9+.

**Comment by pat-alt** [comment]
@jeremiedb thanks for flagging. I guess this may explain why the current dev version of Flux is also bound to `1.9`? Not entirely sure though.

I'll add a note about this to the docs for the NeuroTreeExt in CounterfactualExplanations.jl. And thanks for merging the other PR from yesterday.

**Comment by pat-alt** [comment]
Oh I'm now seeing you've changed that compat entry back here, no worries. I'll run tests for the extension on 1.9+ and add a note. Thanks!

**Edit**: Actually, I still need NeuroTreeModels in the test environment to test the extension on versions 1.9+. I think that for now this means I just won't be able to include tests for it all, unless I remove backward compatibility from CounterfactualExplanations.jl.

**Comment by jeremiedb** [comment]
> **Edit**: Actually, I still need NeuroTreeModels in the test environment to test the extension on versions 1.9+. I think that for now this means I just won't be able to include tests for it all, unless I remove backward compatibility from CounterfactualExplanations.jl.

For clarification, is the concern that you want to maintain the compatibility of `CounterfactualExplanations.jl` with Julia 1.6 and not increase it's lower bound to 1.9? 
 
Wold it be possible to have the NeuroTreeModelsExt only available if Julia >= 1.9, for example by not loading the extension if conditional on julia version? Actually,  since the extension capability is introduced with Julia 1.9, I think that just commenting out the inclusion of the extension could  do it: 

```julia
if !isdefined(Base, :get_extension)
    # include("../ext/EvoTreesCUDAExt/EvoTreesCUDAExt.jl") # commenting out the inclusion of the extention because of compat with julia 1.9+
end
```

**Comment by pat-alt** [comment]
> For clarification, is the concern that you want to maintain the compatibility of `CounterfactualExplanations.jl` with Julia 1.6 and not increase it's lower bound to 1.9?

Yes, exactly.

> Wold it be possible to have the NeuroTreeModelsExt only available if Julia >= 1.9, for example by not loading the extension if conditional on julia version? 

That's basically what I've done in the end. I've just added a separate local environment in the test folder for NeuroTreeModels and activate that only on >= 1.9: https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/tree/main/test/models/neurotree

So ultimately, no issues anymore on my end.

Thanks!

**Pull request merged**
